# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/maswangy/work/zynq_new/10_Advanced/myproject/00_hdmi/first.cache/wt [current_project]
set_property parent.project_path /home/maswangy/work/zynq_new/10_Advanced/myproject/00_hdmi/first.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/maswangy/work/zynq_new/10_Advanced/myproject/00_hdmi/first.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/maswangy/work/zynq_new/10_Advanced/myproject/00_hdmi/first.srcs/sources_1/imports/first.srcs/asyn_rst_syn.v
  /home/maswangy/work/zynq_new/10_Advanced/myproject/00_hdmi/first.srcs/sources_1/imports/first.srcs/dvi_encoder.v
  /home/maswangy/work/zynq_new/10_Advanced/myproject/00_hdmi/first.srcs/sources_1/imports/first.srcs/dvi_transmitter_top.v
  /home/maswangy/work/zynq_new/10_Advanced/myproject/00_hdmi/first.srcs/sources_1/imports/first.srcs/serializer_10_to_1.v
  /home/maswangy/work/zynq_new/10_Advanced/myproject/00_hdmi/first.srcs/sources_1/imports/first.srcs/video_display.v
  /home/maswangy/work/zynq_new/10_Advanced/myproject/00_hdmi/first.srcs/sources_1/imports/first.srcs/video_driver.v
  /home/maswangy/work/zynq_new/10_Advanced/myproject/00_hdmi/first.srcs/sources_1/imports/first.srcs/hdmi_colorbar_top.v
}
read_ip -quiet /home/maswangy/work/zynq_new/10_Advanced/myproject/00_hdmi/first.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/maswangy/work/zynq_new/10_Advanced/myproject/00_hdmi/first.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/maswangy/work/zynq_new/10_Advanced/myproject/00_hdmi/first.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/maswangy/work/zynq_new/10_Advanced/myproject/00_hdmi/first.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/maswangy/work/zynq_new/10_Advanced/myproject/00_hdmi/first.srcs/constrs_1/new/new.xdc
set_property used_in_implementation false [get_files /home/maswangy/work/zynq_new/10_Advanced/myproject/00_hdmi/first.srcs/constrs_1/new/new.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top hdmi_colorbar_top -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef hdmi_colorbar_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file hdmi_colorbar_top_utilization_synth.rpt -pb hdmi_colorbar_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
